/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xxnan_blockinger_game_utils_JniUtil */

#ifndef _Included_org_xxnan_blockinger_game_utils_JniUtil
#define _Included_org_xxnan_blockinger_game_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xxnan_blockinger_game_utils_JniUtil
 * Method:    getIdFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xxnan_blockinger_game_utils_JniUtil_getIdFromJni
  (JNIEnv *, jclass);

/*
 * Class:     org_xxnan_blockinger_game_utils_JniUtil
 * Method:    getSecretFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xxnan_blockinger_game_utils_JniUtil_getSecretFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
