//
// Created by xxnan on 2017/9/1.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xxnan_blockinger_game_utils_JniUtil */

#ifndef _Included_org_xxnan_blockinger_game_utils_JniUtil
#define _Included_org_xxnan_blockinger_game_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xxnan_blockinger_game_utils_JniUtil
 * Method:    getIdFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xxnan_blockinger_game_utils_JniUtil_getIdFromJni
  (JNIEnv *env, jclass jobj){
  return (*env)->NewStringUTF(env,"8e2be0b402bf5bb7");
  }

/*
 * Class:     org_xxnan_blockinger_game_utils_JniUtil
 * Method:    getSecretFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xxnan_blockinger_game_utils_JniUtil_getSecretFromJni
  (JNIEnv *env, jclass jobj){
  return (*env)->NewStringUTF(env,"60e9003b81392c29");
  }

#ifdef __cplusplus
}
#endif
#endif


